fullsuite-se/suitelifer-frontend

src/pages/guest/Careers.jsx
Refactor Careers page styles for improved layout and responsiveness on tablet and desktop
=> Refactored: Careers Page Hero Section

src/pages/guest/AboutUs.jsx
fix: adjust padding in AboutUs section for improved layout
=> Refactored: Core Values Section

package-lock.json, package.json, src/components/layout/PageMeta.jsx, src/components/news/ArticleDetails.jsx, src/main.jsx, src/pages/guest/AboutUs.jsx, src/pages/guest/Blog.jsx, src/pages/guest/Careers.jsx, src/pages/guest/Contact.jsx, src/pages/guest/Home.jsx, src/pages/guest/News.jsx
Improved SEO meta tag handling for better optimization
=> SEO Optimization

src/App.jsx
Improve Import Structure For Cleaner Code
=> Improve Import Structure For Cleaner Code

src/components/employee/EmployeeDrawer.jsx
refactor EmployeeDrawer to use dynamic service icons and improvement
=> feat: refactor EmployeeDrawer to use dynamic service icons and improvement

src/components/admin/JobCourse.jsx, src/components/admin/SpotifyEpisode.jsx, src/pages/admin/AdminContents.jsx
table and button functions (CRUD)
=> Jobcourse Initial Set-up

src/components/admin/JobCourse.jsx, src/components/admin/PersonalityTest.jsx
=> Testpersonality Initial Set-up

src/components/employee/EmployeeAside.jsx, src/components/navigation/CMSNavigation.jsx
Local Storage for better User Experience
=> Local Storage for better User Experience

src/components/admin/Testimonials.jsx
=> fix: adjust visibility column header and increase textarea rows

src/components/admin/FooterContent.jsx
=> Rename input field for certification image URL in FooterContent 

src/App.jsx
=> Ojt dev shopfullfeatures v1

src/pages/employee/EmployeeCheerPage.jsx
- Redesigned the heartbits display section to improve visual clarity and user experience.
- Introduced a vertical divider between remaining heartbits and received heartbits.
- Added labels "Remaining" and "Received" for better context on the displayed values.
=> feat: enhance layout of heartbits display in EmployeeCheerPage

package-lock.json, package.json, src/components/suitebite/ProductCard.jsx, src/components/suitebite/ProductImageCarousel.jsx, src/components/suitebite/admin/AddProductForm.jsx, src/components/suitebite/admin/ImageTest.jsx, src/components/suitebite/admin/ProductImageCarousel.jsx, src/components/suitebite/admin/ProductImageUpload.jsx, src/utils/suitebiteAPI.js
Summary
Enhanced frontend with product image carousel components, improved Cloudinary upload handling for new products, and various UI improvements.
- ✅ Product image carousel components for better image display
- ✅ Fixed Cloudinary image upload for new products (generic endpoint)
- ✅ Enhanced product add/edit form with better image handling
- ✅ UI improvements and component refactoring
- ✅ Better error handling in image upload flow
- ProductImageUpload.jsx - Fixed upload logic for new products
- AddProductForm.jsx - Enhanced with image carousel integration
- ProductImageCarousel.jsx - New carousel component
- suitebiteAPI.js - Added generic upload endpoint
=> Frontend: Product image carousel, improved upload handling, and UI enhancements

src/api/pointsShopApi.js, src/pages/employee/EmployeeCheerPage.jsx
Fixed and Improved the leaderboard for better handling of Users points into the leaderboard. && Improved UI look of the Employee Cheer A Peer
=> Ojt dev jelo debug4

package-lock.json, package.json, src/pages/employee/EmployeeCheerPage.jsx
This pull request makes significant updates to the `EmployeeCheerPage` component in `src/pages/employee/EmployeeCheerPage.jsx`, focusing on removing unused Framer Motion features, improving UI/UX design, and enhancing code maintainability. Additionally, it updates the `framer-motion` dependency in `package.json`.
* Updated `framer-motion` to version `^12.23.6` in `package.json` to ensure compatibility and remove unused features.
* Removed all imports and logic related to Framer Motion, including `motion`, `AnimatePresence`, `confettiAnimating`, and associated animation helpers. This simplifies the component by eliminating unused animation logic. [[1]](diffhunk://#diff-4b359b0523abe982378f4ef0fd73e2ef743bb63f411b6c66b3dafc1035e52d63R17-R19) …
=> Ojt dev UI improvs

src/pages/employee/EmployeeCheerPage.jsx
- Implemented state management for editing and deleting comments.
- Added mutation hooks for updating and deleting cheer comments with success/error handling.
- Enhanced UI to allow users to edit or confirm deletion of their comments directly within the interface.
=> Add comment editing and deletion functionality in EmployeeCheerPage

src/pages/employee/EmployeeCheerPage.jsx, src/pages/employee/EmployeePointsDashboard.jsx
- Updated the cheer points display to include a heart icon and the term 'bits' for clarity.
- Modified the transaction amount display in EmployeePointsDashboard to differentiate between 'pts' and 'bits' based on transaction type.
=> Enhance points display in EmployeeCheerPage and EmployeePointsDashboard

src/pages/employee/EmployeeCheerPage.jsx
This pull request makes several updates to the `EmployeeCheerPage` component in `src/pages/employee/EmployeeCheerPage.jsx`, focusing on improving the user interface and code quality. The most notable changes include enhancing the leaderboard card's appearance, fixing a missing variable declaration, and improving the leaderboard's scrolling behavior.
* Added a hover effect (`hover:scale-[1.02]`) and box shadow to the leaderboard card for a more interactive and visually appealing design. (`[src/pages/employee/EmployeeCheerPage.jsxL1299-R1302](diffhunk://#diff-4b359b0523abe982378f4ef0fd73e2ef743bb63f411b6c66b3dafc1035e52d63L1299-R1302)`)
* Fixed a missing variable declaration for `leaderboard`, which now defaults to an empty array to prevent potential runtime errors. …
=> Refactor date filtering and enhance UI in EmployeeCheerPage

src/components/suitebite/OrderHistory.jsx, src/components/suitebite/ShopTabContent.jsx, src/components/suitebite/ShoppingCart.jsx, src/components/suitebite/admin/OrderManagement.jsx, src/pages/employee/SuitebiteShop.jsx
=> feat: Optimize Shop Performance & Fix Buy Now

src/pages/employee/SuitebiteShop.jsx
- Update handleCheckout to refresh cart from backend instead of clearing it
- Fix issue where selecting 1 out of 4 items cleared entire cart
- Maintain remaining items in cart after selective checkout
=> Fix checkout process - prevent entire cart clearing

src/api/pointsSystemApi.js, src/components/suitebite/OrderHistory.jsx, src/components/suitebite/ProductDetailModal.jsx, src/components/suitebite/ShopTabContent.jsx, src/components/suitebite/ShoppingCart.jsx, src/components/suitebite/admin/OrderManagement.jsx, src/pages/employee/EmployeeCheerAPeer.jsx, src/pages/employee/EmployeePointsDashboard.jsx, src/pages/employee/SuitebiteShop.jsx, src/utils/suitebiteAPI.js
- Performance optimizations:
* Added 5-minute cache for shop products to prevent unnecessary reloads
* Added 2-minute cache for order management with smart invalidation
* Optimized cart operations to only update cart/heartbits, not reload products
* Added refresh functions for when full reload is needed
- UI/UX improvements:
* Enhanced order management UI with compact design
* Improved order details modal layout
* Better loading states and error handling
* Custom confirmation modals instead of browser alerts
- Code cleanup:
* Removed excessive debug logging from all components
* Cleaned up console output for better developer experience
* Optimized API calls and state management
* Improved error handling and notifications
- Points dashboard integration:
* Added localStorage event system …
=> feat: optimize frontend performance and clean up debug logs

src/components/suitebite/ProductCard.jsx, src/components/suitebite/ProductDetailModal.jsx, src/components/suitebite/ShopTabContent.jsx, src/utils/suitebiteAPI.js
- Fix add to cart balance validation - users can now add items regardless of balance
- Fix Buy Now quantity preservation in product modal
- Add balance validation for Buy Now button in product cards
- Add modal system to ShopTabContent for consistent UX
- Update ProductDetailModal to remove balance check from Add to Cart button
- Update suitebiteAPI to route user/admin delete requests correctly
- Ensure proper quantity flow from product card to modal
- Add visual feedback for insufficient balance in Buy Now buttons
- Maintain consistent UX across all shopping cart operations
=> feat: Complete frontend order deletion and cart UX improvements

src/components/suitebite/admin/UserHeartbitsManagement.jsx, src/pages/employee/EmployeePointsDashboard.jsx
- Updated role label mapping to use uppercase for consistency.
- Adjusted layout and styling of user cards for better visual appeal.
- Increased the height of the users table container and modified background gradient.
- Improved user selection feedback with updated styles and sizes for icons.
- Enhanced display of user information, including name, role, and heartbits balance.
=> refactor: enhance UserHeartbitsManagement UI and improve role label handling

src/components/suitebite/ProductCard.jsx, src/pages/employee/EmployeePointsDashboard.jsx
This pull request focuses on improving the visual design and user experience of key components by refining styles, adding dynamic interactions, and enhancing consistency in the UI. The most important changes include updates to the `ProductCard` component for hover effects and shadow transitions, and adjustments to the `PointsDashboard` for border radius and message styling.
* **`ProductCard` hover effects and shadow transitions**: Added a dynamic scaling effect (`hover:scale-105`) and interactive shadow transitions on hover using `onMouseEnter` and `onMouseLeave` handlers. This enhances the visual feedback when users interact with product cards. (`src/components/suitebite/ProductCard.jsx`, [src/components/suitebite/ProductCard.jsxL183-R192](diffhunk://#diff-dea005f4abc949907c73537ef2be7a2c …
=> UI adjustments

src/components/suitebite/ProductCard.jsx
- Removed inline styles for box shadow on hover, replacing them with a class-based approach for cleaner code.
- Enhanced hover shadow effect for improved visual feedback while maintaining overall design consistency.
=> refactor: simplify ProductCard hover effects and styling

src/pages/employee/EmployeeCheerAPeer.jsx
- Added validation to ensure a message is entered before sending cheers, enhancing user experience.
- Updated UI to indicate that the message field is now required, improving clarity for users.
=> feat: enforce message requirement in CheerPage for user feedback
